load_sequence:         8

# Source Config
source_adapter:        mssql
source_table:          "Users"
column_mappings:
  "Users.status": status
  "Users.department": department
  "Users.nvtgc": nvtgc
filter_raw: |
                      EXISTS (
                        SELECT *
                        FROM  Transactions T
                        WHERE T.username = Users.username
                      )
export_file_name:      "user_infos.csv"

# Target Config
target_adapter:        csv
truncate_before_load:  "yes"
target_model:          "Illiad::UserInfo"
# transformations:
#   department:
#     "UNDC.*": "Conversion Test 1"
#     "URBS.*": "Conversion Test 2"
#     "SSE": "Conversion Test 3"
#     ".*": "Conversion Test Others"
