load_sequence:         1
target_model:          "GateCount::CardSwipe"
target_adapter:        "csv"
truncate_before_load:  "no"
file_name:             "gate.csv"
target_mappings:
  swipe_date: date
#  swipe_time: time
  swipe_time: id
  door_name: door_name
  affiliation_desc: affiliation_desc
  center_desc: center_desc
  dept_desc: dept_desc
  usc_desc: usc_desc
