version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0
  gitleaks: upenn-libraries/gitleaks@0.1.1

commands:
  molecule_test:
    description: Run the `molecule test` command within a role directory
    parameters:
      role:
        description: Name of the Ansible role
        type: string
    steps:
      - run:
          command: molecule test
          working_directory: ansible/roles/<< parameters.role >>

jobs:
  deploy:
    docker:
      - image: quay.io/upennlibraries/ansible:2.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 70:5d:2c:e0:35:ce:a0:c6:85:ba:12:b2:72:a8:9e:b0
      - run:
          working_directory: ~/project/ansible
          command: |
            ansible-playbook \
              -vvvv \
              -i inventories/test \
              -e 'ansible_ssh_common_args="-o ProxyCommand=\"ssh -vvv -W %h:%p $SSH_DEPLOY_USER@$SSH_DEPLOY_HOST -p $SSH_DEPLOY_PORT\""' \
              --vault-id vault_passwd.py \
              metridoc.yml
  test_role:
    description: Test an Ansible role using Molecule
    parameters:
      role:
        description: Name of the Ansible role
        type: string
    docker:
      - image: quay.io/ansible/molecule:2.22rc3
    steps:
      - checkout
      - setup_remote_docker
      - molecule_test:
          role: << parameters.role >>

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v2.0.0
          options: --redact --config=${CIRCLE_WORKING_DIRECTORY}/.gitleaks.toml --branch=${CIRCLE_BRANCH}
      # - docker-publish/publish:
      #     context: quay.io
      #     registry: quay.io
      #     image: upennlibraries/metridoc
      #     tag: $CIRCLE_BRANCH
      #     label_prefix: edu.upenn.library
      #     requires:
      #       - gitleaks/check_local
      # - test_role:
      #     name: test_jenkins_manager_role
      #     role: jenkins_manager
      #     requires:
      #       - gitleaks/check_local
      # - test_role:
      #     name: test_metridoc_manager_role
      #     role: metridoc_manager
      #     requires:
      #       - gitleaks/check_local
      # - test_role:
      #     name: test_postgres_primary_manager_role
      #     role: postgres_primary_manager
      #     requires:
      #       - gitleaks/check_local
      # - test_role:
      #     name: test_postgres_replica_manager_role
      #     role: postgres_replica_manager
      #     requires:
      #       - gitleaks/check_local
      - deploy:
          filters:
            branches:
              only: circleci_cd
          # requires:
          #   - docker-publish/publish
            # - test_jenkins_manager_role
            # - test_metridoc_manager_role
            # - test_postgres_primary_manager_role
            # - test_postgres_replica_manager_role
