---
institution_code: 'UPENN'
host:             '<%= ENV["BORROWDIRECT_RESHARE_HOST"] %>'
port:             '<%= ENV["BORROWDIRECT_RESHARE_PORT"] %>'
database:         '<%= ENV["BORROWDIRECT_RESHARE_DB"] %>'
username:         '<%= ENV["BORROWDIRECT_RESHARE_UID"] %>'
password:         '<%= ENV["BORROWDIRECT_RESHARE_PWD"] %>'
pool:             5
timeout:          120000
export_folder:    '/tmp/borrowdirect_reshare/'
