load_sequence:         2
target_model:          "Illiad::LenderGroup"
truncate_before_load:  "yes"
filter:                ""
select_sql:            "DISTINCT GroupNumber, LenderString"
source_tables:         "GroupsLink"
unique_column:         "GroupNumber"
column_mappings:
  GroupNumber:  group_no
  LenderString: lender_code
