---
- name: create config directory
  file:
    path: '{{ config_dir }}/postgres/primary'
    state: directory

- name: copy docker compose file
  copy:
    src: docker-compose.yml
    dest: '{{ config_dir }}/postgres/primary/docker-compose.yml'

- name: create pg_hba config file
  template:
    src: pg_hba.conf.j2
    dest: '{{ config_dir }}/postgres/primary/pg_hba.conf'

- name: create docker secret for init_primary query
  docker_secret:
    name: metridoc_postgres_init_primary_{{ postgres_init_primary_version }}
    data: '{{ lookup("template", "init_primary.sql.j2") }}'
    state: present
  no_log: true
  tags:
    - docker

- name: create docker secret for database password
  docker_secret:
    name: metridoc_postgres_database_password_{{ postgres_database_password_version }}
    data: '{{ postgres_database_password }}'
    state: present
  no_log: true
  tags:
    - docker

- name: label primary swarm node
  docker_node:
    hostname: '{{ postgres_primary_swarm_node }}'
    labels:
      postgres-primary: 'true'
  tags:
    - docker

- name: start docker services
  environment: '{{ docker_stack_env }}'
  command: docker stack deploy -c {{ config_dir }}/postgres/primary/docker-compose.yml metridoc
  changed_when: false
  tags:
    - docker

- debug:
    msg: Docker services are deploying in the background. Check host to see progress.
  tags:
    - docker
