---
load_sequence: 2
target_model: "UpennEzproxy::EzpaarseJob"
target_adapter: "native_sql"
truncate_before_load: "no"
sqls:
  - |
      UPDATE upenn_ezproxy_ezpaarse_jobs
      SET (
        statistical_category_1,
        statistical_category_2,
        statistical_category_3,
        statistical_category_4,
        statistical_category_5,
        user_group,
        school,
        penn_id
      ) = (
        upenn_alma_demographics.statistical_category_1,
        upenn_alma_demographics.statistical_category_2,
        upenn_alma_demographics.statistical_category_3,
        upenn_alma_demographics.statistical_category_4,
        upenn_alma_demographics.statistical_category_5,
        upenn_alma_demographics.user_group,
        upenn_alma_demographics.school,
        upenn_alma_demographics.penn_id
      )
      FROM upenn_alma_demographics
      WHERE
        upenn_ezproxy_ezpaarse_jobs.penn_id IS NULL
        AND upenn_ezproxy_ezpaarse_jobs.login IS NOT NULL
        AND upenn_alma_demographics.pennkey = upenn_ezproxy_ezpaarse_jobs.login;
