---
institution_code: 'BROWN'
host:             '<%= ENV["BROWN_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["BROWN_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["BROWN_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["BROWN_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["BROWN_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
tds_version:      7.3
export_folder:    '/tmp/brown_illiad/'
import_folder:    '/Users/jkiser/Desktop/illiadbrown'
batch_size:       10000
