load_sequence:         1

# Source Config
source_adapter:        postgres
source_table:          "reshare_rs.patron_request"
column_mappings:
  "pr_id": pr_id
  "pr_version": pr_version
  "pr_date_created": pr_date_created
  "pr_pub_date": pr_pub_date
  "pr_edition": pr_edition
  "__start": __start

export_file_name:      "reshare_patron_requests.csv"
export_filter_date_sql: "__start > ?"


# Target Config
target_adapter:        csv
target_model:          "Reshare::PatronRequest"
truncate_before_load:  "no"
incremental_filter_column: "__start"
