load_sequence:         6

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.req_overdue"
column_mappings:
  "ro_requester": ro_requester
  "ro_requester_nice_name": ro_requester_nice_name
  "ro_hrid": ro_hrid
  "ro_title": ro_title
  "ro_requester_sym": ro_requester_sym
  "ro_requester_url": ro_requester_url
  "ro_supplier_sym": ro_supplier_sym
  "ro_req_state": ro_req_state
  "ro_due_date_rs": ro_due_date_rs
  "ro_return_shipped_date": ro_return_shipped_date
  "ro_last_updated": ro_last_updated

export_file_name:      "reshare_req_overdues.csv"

# Target Config
target_adapter:        csv
target_model:          "Reshare::ReqOverdue"

# Run the full truncation every time
truncate_before_load:  "yes"
