load_sequence:         7

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.sup_overdue"
column_mappings:
  "so_supplier": so_supplier
  "so_supplier_nice_name": so_supplier_nice_name
  "so_hrid": so_hrid
  "so_title": so_title
  "so_requester_sym": so_requester_sym
  "so_supplier_url": so_supplier_url
  "so_supplier_sym": so_supplier_sym
  "so_res_state": so_res_state
  "so_due_date_rs": so_due_date_rs
  "so_local_call_number": so_local_call_number
  "so_item_barcode": so_item_barcode
  "so_last_updated": so_last_updated

export_file_name:      "reshare_sup_overdues.csv"
export_filter_date_sql: "so_last_updated > ?"


# Target Config
target_adapter:        csv
target_model:          "Reshare::SupOverdue"
truncate_before_load:  "yes"
