load_sequence:         8

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.rtat_reqs"
column_mappings:
  "rtr_requester": rtr_requester
  "rtr_requester_nice_name": rtr_requester_nice_name
  "rtr_hrid": rtr_hrid
  "rtr_title": rtr_title
  "rtr_call_number": rtr_call_number
  "rtr_barcode": rtr_barcode
  "rtr_supplier": rtr_supplier
  "rtr_supplier_nice_name": rtr_supplier_nice_name 
  "rtr_date_created": rtr_date_created
  "rtr_id": rtr_id

export_file_name:      "reshare_rtat_reqs.csv"

# Target Config
target_adapter:        csv
target_model:          "Reshare::RtatReq"
truncate_before_load:  "yes"
