load_sequence:         9

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.rtat_ship"
column_mappings:
  "rts_requester": rts_requester
  "rts_date_created": rts_date_created
  "rts_req_id": rts_req_id
  "rts_from_status": rts_from_status
  "rts_to_status": rts_to_status

export_file_name:      "reshare_rtat_ships.csv"

# Target Config
target_adapter:        csv
target_model:          "Reshare::RtatShip"
truncate_before_load:  "yes"
