load_sequence:         9

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.req_stats"
column_mappings:
  "rs_requester": rs_requester
  "rs_requester_nice_name": rs_requester_nice_name
  "rs_id": rs_id
  "rs_req_id": rs_req_id
  "rs_date_created": rs_date_created
  "rs_from_status": rs_from_status
  "rs_to_status": rs_to_status
  "rs_message": rs_message


export_file_name:      "reshare_req_stats.csv"
export_filter_date_sql: "rs_date_created > ?"

# Filter out Bobst and South Charleston
# They cause double counting for NYU and Marshall University
filters:
  - "rs_requester_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"

# Target Config
target_adapter:        csv
target_model:          "Reshare::ReqStat"
truncate_before_load:  "no"
incremental_filter_column: "rs_date_created"
# No columns, purely run on the incremental date
