load_sequence:         10

target_adapter:        native_sql
target_model:          "Reshare::RtatReq"
truncate_before_load:  "no"


sql: |
      INSERT INTO reshare_rtat_reqs (
        rtr_requester,
        rtr_requester_nice_name,
        rtr_hrid,
        rtr_title,
        rtr_call_number
        rtr_barcode,
        rtr_supplier,
        rtr_supplier_nice_name,
        rtr_date_created,
        rtr_id
      )
      SELECT DISTINCT
        pr.origin AS rtr_requester,
        de1.de_name AS rtr_requester_nice_name,
        pr.pr_hrid AS rtr_hrid,
        pr.pr_title AS rtr_title,
        pr.pr_local_call_number AS rtr_call_number,
        pr.pr_selected_item_barcode AS rtr_barcode,
        pr.pr_resolved_sup_inst_symbol_fk AS rtr_supplier,
        de2.de_name AS rtr_supplier_nice_name,
        pr.pr_date_created AS rtr_date_created,
        pr.pr_id AS rtr_id
      FROM
        reshare_patron_request pr
        LEFT JOIN reshare_symbol s1 ON pr.pr_resolved_req_inst_symbol_fk = s1.sym_id
          AND pr.origin = s1.origin
        LEFT JOIN reshare_symbol s2 ON pr.pr_resolved_sup_inst_symbol_fk = s2.sym_id
          AND pr.origin = s2.origin
        LEFT JOIN reshare_directory_entry de1 ON s1.sym_owner_fk = de1.de_id
          AND s1.origin = de1.origin
        LEFT JOIN reshare_directory_entry de2 ON s2.sym_owner_fk = de2.de_id
          AND s2.origin = de2.origin
      WHERE
        pr.pr_is_requester IS TRUE
        AND pr.pr_hrid IS NOT NULL
        AND rtr_date_created < (
          SELECT
            MAX(rtr_date_created)
          FROM reshare_rtat_reqs
        )
      ON CONFLICT DO NOTHING;

# # Source Config
# source_adapter:        postgres
# source_table:          "reshare_derived.rtat_reqs"
# column_mappings:
#   "rtr_requester": rtr_requester
#   "rtr_requester_nice_name": rtr_requester_nice_name
#   "rtr_hrid": rtr_hrid
#   "rtr_title": rtr_title
#   "rtr_call_number": rtr_call_number
#   "rtr_barcode": rtr_barcode
#   "rtr_supplier": rtr_supplier
#   "rtr_supplier_nice_name": rtr_supplier_nice_name
#   "rtr_date_created": rtr_date_created
#   "rtr_id": rtr_id
#
# export_file_name:      "reshare_rtat_reqs.csv"
# export_filter_date_sql: "rtr_date_created > ?"
#
# # Filter out Bobst and South Charleston
# # They cause double counting for NYU and Marshall University
# filters:
#   - "rtr_requester_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"
#   - "rtr_supplier_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"
#
#
# # Target Config
# target_adapter:        csv
# target_model:          "Reshare::RtatReq"
# truncate_before_load:  "no"
# incremental_filter_column: "rtr_date_created"
#
# unique_keys: ["rtr_hrid"]
# upsert: false
