load_sequence:         10

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.rtat_rec"
column_mappings:
  "rtre_requester": rtre_requester
  "rtre_date_created": rtre_date_created
  "rtre_req_id": rtre_req_id
  "rtre_status": rtre_status

export_file_name:      "reshare_rtat_recs.csv"
export_filter_date_sql: "rtre_date_created > ?"

# Target Config
target_adapter:        csv
target_model:          "Reshare::RtatRec"
truncate_before_load:  "yes"
