load_sequence:         11

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.stat_reqs"
column_mappings:
  "str_supplier": str_supplier 
  "str_supplier_nice_name": str_supplier_nice_name
  "str_hrid": str_hrid
  "str_title": str_title
  "str_call_number": str_call_number
  "str_barcode": str_barcode
  "str_requester": str_requester
  "str_requester_nice_name": str_requester_nice_name
  "str_date_created": str_date_created
  "str_id": str_id

export_file_name:      "reshare_stat_reqs.csv"
export_filter_date_sql: "str_date_created > ?"

# Target Config
target_adapter:        csv
target_model:          "Reshare::StatReq"
truncate_before_load:  "yes"
