load_sequence:         12

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.stat_assi"
column_mappings:
  "sta_supplier": sta_supplier
  "sta_date_created": sta_date_created
  "sta_req_id": sta_req_id
  "sta_from_status": sta_from_status
  "sta_to_status": sta_to_status

export_file_name:      "reshare_stat_assis.csv"
export_filter_date_sql: "sta_date_created > ?"

# Target Config
target_adapter:        csv
target_model:          "Reshare::StatAssi"
truncate_before_load:  "yes"
