load_sequence:         13

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.stat_fill"
column_mappings:
  "stf_supplier": stf_supplier
  "stf_date_created": stf_date_created
  "stf_req_id": stf_req_id
  "stf_from_status": stf_from_status
  "stf_to_status": stf_to_status


export_file_name:      "reshare_stat_fills.csv"
export_filter_date_sql: "stf_date_created > ?"

# Target Config
target_adapter:        csv
target_model:          "Reshare::StatFill"
truncate_before_load:  "yes"
