load_sequence:         13

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.sup_stats"
column_mappings:
  "ss_supplier": ss_supplier
  "ss_supplier_nice_name": ss_supplier_nice_name
  "ss_id": ss_id
  "ss_req_id": ss_req_id
  "ss_date_created": ss_date_created
  "ss_from_status": ss_from_status
  "ss_to_status": ss_to_status
  "ss_message": ss_message

export_file_name:      "reshare_sup_stats.csv"
export_filter_date_sql: "ss_date_created > ?"

# Filter out Bobst and South Charleston
# They cause double counting for NYU and Marshall University
filters:
  - "ss_supplier_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"

# Target Config
target_adapter:        csv
target_model:          "Reshare::SupStat"
truncate_before_load:  "no"
incremental_filter_column: "ss_date_created"
