load_sequence:         14

# Source Config
source_adapter:        postgres
source_table:          "reshare_derived.stat_ship"
column_mappings:
  "sts_supplier": sts_supplier
  "sts_date_created": sts_date_created
  "sts_req_id": sts_req_id
  "sts_from_status": sts_from_status
  "sts_to_status": sts_to_status

export_file_name:      "reshare_stat_ships.csv"
export_filter_date_sql: "sts_date_created > ?"

# Target Config
target_adapter:        csv
target_model:          "Reshare::StatShip"
truncate_before_load:  "no"
incremental_filter_column: "sts_date_created"
