load_sequence:         14

# Target Config
target_adapter:        csv
target_model:          "Reshare::StatReq"
truncate_before_load:  "no"

sql : |
        INSERT INTO reshare_stat_reqs (
          str_supplier,
          str_supplier_nice_name,
          str_hrid,
          str_title,
          str_call_number,
          str_barcode,
          str_requester
          str_requester_nice_name,
          str_date_created,
          str_id
        )
        SELECT DISTINCT
          pr.origin AS str_supplier,
          names.de_name AS str_supplier_nice_name,
          pr.pr_hrid AS str_hrid,
          pr.pr_title AS str_title,
          pr.pr_local_call_number AS str_call_number,
          pr.pr_selected_item_barcode AS str_barcode,
          pr.pr_resolved_req_inst_symbol_fk AS str_requester,
          de.de_name AS str_requester_nice_name,
          pr.pr_date_created AS str_date_created,
          pr.pr_id AS str_id
        FROM
          reshare_patron_requests pr
        LEFT JOIN reshare_symbols s2
        ON pr.pr_resolved_req_inst_symbol_fk = s2.sym_id
        LEFT JOIN reshare_directory_entries de
        ON s2.sym_owner_fk = de.de_id
          AND s2.origin = de.origin
        JOIN (
          SELECT
            de2.origin,
            de2.de_name
          FROM
            reshare_directory_entries de2
          WHERE
            de2.de_parent IS NULL
            AND de2.de_status_fk IS NOT NULL
          ) AS names ON pr.origin = names.origin
        WHERE
          pr.pr_is_requester IS FALSE
          AND pr.pr_hrid IS NOT NULL
          AND pr.pr_resolved_req_inst_symbol_fk != pr.pr_resolved_sup_inst_symbol_fk
          AND pr.pr_date_created > (
            SELECT
              MAX(str_date_created)
            FROM reshare_stat_reqs
          )
        ON CONFLICT DO NOTHING;


# # Source Config
# source_adapter:        postgres
# source_table:          "reshare_derived.stat_reqs"
# column_mappings:
#   "str_supplier": str_supplier
#   "str_supplier_nice_name": str_supplier_nice_name
#   "str_hrid": str_hrid
#   "str_title": str_title
#   "str_call_number": str_call_number
#   "str_barcode": str_barcode
#   "str_requester": str_requester
#   "str_requester_nice_name": str_requester_nice_name
#   "str_date_created": str_date_created
#   "str_id": str_id
#
# export_file_name:      "reshare_stat_reqs.csv"
# export_filter_date_sql: "str_date_created > ?"
#
# # Filter out Bobst and South Charleston
# # They cause double counting for NYU and Marshall University
# filters:
#   - "str_supplier_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"
#   - "str_requester_nice_name NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"
#
#
# # Target Config
# target_adapter:        csv
# target_model:          "Reshare::StatReq"
# truncate_before_load:  "no"
# incremental_filter_column: "str_date_created"
#
# unique_keys: ["str_supplier", "str_id"]
# upsert: false
