load_sequence:         19

# Target Configuration
target_adapter: 'native_sql'
target_model: "Reshare::SupTatStat"
truncate_before_load:  "no"

sql: |
        INSERT INTO reshare_sup_tat_stats (
          stst_supplier,
          stst_date_created,
          stst_req_id,
          stst_from_status,
          stst_to_status,
          stst_message
        )
        SELECT DISTINCT
          ss_supplier_nice_name AS stst_supplier,
          (array_agg(ss_date_created ORDER BY ss_date_created ASC))[1] AS stst_date_created,
          ss_req_id AS stst_req_id,
          ss_from_status AS stst_from_status,
          ss_to_status AS stst_to_status,
          ss_message AS stst_message
        FROM
          reshare_sup_stats
        WHERE
          ss_date_created > (
            SELECT
              MAX(stst_date_created)
            FROM reshare_sup_tat_stats
          )
        GROUP BY
          stst_req_id,
          stst_from_status,
          stst_to_status,
          stst_message,
          stst_supplier
        ON CONFLICT DO NOTHING;

# # Source Config
# source_adapter:        postgres
# source_table:          "reshare_derived.sup_tat_stats"
# column_mappings:
#   "stst_supplier": stst_supplier
#   "stst_date_created": stst_date_created
#   "stst_req_id": stst_req_id
#   "stst_from_status": stst_from_status
#   "stst_to_status": stst_to_status
#   "stst_message": stst_message
#
# export_file_name:      "reshare_sup_tat_stats.csv"
# export_filter_date_sql: "stst_date_created > ?"
#
# filters:
#   - "stst_supplier NOT IN ('Bobst Circulation Desk', 'South Charleston Campus Collection')"
#
# # Target Config
# target_adapter:        csv
# target_model:          "Reshare::SupTatStat"
# truncate_before_load:  "no"
# incremental_filter_column: "stst_date_created"
