load_sequence:         4

# Source Config
source_adapter:        mssql
source_table:          "id_audit"
column_mappings:
  "id_audit.request_number": request_number
  "id_audit.time_stamp": ship_date
  "id_audit.exception_code": exception_code
  "d.date_processed": process_date 
join_tables:
  - "LEFT JOIN id_delivery d ON id_audit.request_number = d.request_number"
filters:
  - "id_audit.exception_code <> 'NULL'"
export_file_name:      "ship_dates.csv"
export_filter_date_sql: "id_audit.time_stamp > ?"
export_filter_date_range_sql: "id_audit.time_stamp > ? AND id_audit.time_stamp < ?"


# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::ShipDate"
purge_legacy_data_before_load:  "yes"
legacy_filter_date_field: "ship_date"
