load_sequence:         5
target_model:          "Borrowdirect::Institution"
truncate_before_load:  "yes"
filter:                ""
select_sql: |
                       catalog_code AS catalog_code,
                       catalog_code_desc AS institution,
                       catalog_library_id AS library_id

source_tables: |
                       id_catalog_code

unique_column:         "catalog_library_id"
fetch_rows_size:       100
