load_sequence:         5

# Source Config
source_adapter:        mssql
source_table:          "ID_LIBRARY"
column_mappings:
  LIBRARY_ID: library_id
  LIBRARY_SYMBOL: library_symbol
  INSTITUTION_NAME: institution_name
  PRIME_POST_ZIPCODE: prime_post_zipcode
  WEIGHTING_FACTOR: weighting_factor
export_file_name:      "institutions.csv"

# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::Institution"
purge_legacy_data_before_load:  "yes"
