load_sequence:         9
target_adapter:        "native_sql"
target_model:          "Borrowdirect::Bibliography"
sqls:
  - |
                        UPDATE borrowdirect_bibliographies
                        SET oclc = CAST((REGEXP_MATCH(oclc_text, '^([0-9]+)'))[1] AS BIGINT)
