version: '3.7'

services:
  jenkins:
    image: quay.io/upennlibraries/jenkins_docker_client:lts
    deploy:
      placement:
        constraints:
          - node.labels.jenkins == true
    networks:
      - jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    driver: overlay

volumes:
  jenkins_home:
