load_sequence:         5

# Source Config
source_adapter:        postgres
source_table:          "reshare_rs.status"
column_mappings:
  "__start": last_updated
  "__origin": origin

  "st_id": st_id
  "st_version": st_version

  "st_code": st_code

export_file_name:      "reshare_status.csv"
export_filter_date_sql: "__start > ?"

# Target Config
target_adapter:        csv
target_model:          "Rsat::Borrowdirect::Reshare::Status"
truncate_before_load:  "no"
incremental_filter_column: "last_updated"

unique_keys: ["st_id"]
upsert: true
