---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    groups:
      - swarm_managers
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../inventories/molecule/group_vars/
  options:
    skip-tags: docker
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint .
