---
- hosts: swarm_managers
  gather_facts: false
  roles:
    - postgres_primary_manager
    - metridoc_manager

- hosts: swarm_managers
  gather_facts: false
  tasks:
    - name: mount local source repository into development container
      command: >
        docker service update
          --env-add APP_USER_UID={{ rails_app_user_uid }}
          --env-add APP_USER_GID={{ rails_app_user_gid }}
          --mount-add type=bind,source={{ metridoc_repo_dir }},target=/home/app/webapp
          --mount-add type=bind,source={{ ansible_dir }}/local_docker_init.sh,target=/local_docker_init.sh
          --args /local_docker_init.sh
          metridoc_app
    - name: get container id
      command: docker ps -qlf name=metridoc_app
      register: container_id
    - name: migrate and seed database
      command: >
        docker exec
          {{ container_id.stdout }}
          bundle exec rake db:migrate db:seed
