---
load_sequence: 5
target_model: "UpennAlma::Demographic"
target_adapter: "native_sql"
truncate_before_load: "no"
sqls:
  - |
      UPDATE upenn_alma_demographics
      SET school = statistical_category_2
      WHERE statistical_category_2 IS NOT NULL
        AND NOT statistical_category_2 = ''
        AND NOT statistical_category_2 = 'School code and Major code';

  - |
      UPDATE upenn_alma_demographics
      SET school = (
        SELECT upenn_alma_divisions.school
        FROM upenn_alma_divisions
        WHERE
          upenn_alma_divisions.division = upenn_alma_demographics.statistical_category_3
      )
      WHERE upenn_alma_demographics.statistical_category_3 IS NOT NULL
        AND NOT upenn_alma_demographics.statistical_category_3 = ''
        AND upenn_alma_demographics.school IS NULL;

  - |
      UPDATE upenn_alma_demographics
      SET school = (
        SELECT upenn_alma_departments.school
        FROM upenn_alma_departments
        WHERE
          upenn_alma_departments.department_code = LEFT(
            upenn_alma_demographics.statistical_category_5, 2
          )
      )
      WHERE upenn_alma_demographics.statistical_category_5 IS NOT NULL
        AND NOT upenn_alma_demographics.statistical_category_5 = ''
        AND NOT upenn_alma_demographics.statistical_category_5 = '4 digit organization code'
        AND upenn_alma_demographics.school IS NULL;
