---
target_adapter: 'csv'
export_folder: '/tmp/upenn_alma'
institution_code: 'UPENN'

alma_domain: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/analytics/reports?"
alma_apikey: '<%= ENV["ALMA_API_KEY"] %>'
