load_sequence:         7

# Source Config
source_adapter:        mssql
source_table:           Transactions
column_mappings:
  "Tracking.TransactionNumber": transaction_number
  "Transactions.RequestType": request_type
  "Tracking.ChangedTo": status
  "MIN(Tracking.DateTime)": transaction_date
filter_raw: |
                        (
                            Tracking.ChangedTo IN ('Submitted by Customer', 'Request Added Through Client', 'Request Added through Web Platform')
                            OR
                            (
                              Transactions.RequestType = 'Article'
                              AND
                              Tracking.ChangedTo IN ('Delivered To Web')
                            )
                            OR
                            (
                              Transactions.RequestType = 'Loan'
                              AND
                              Tracking.ChangedTo IN ('Item Found')
                            )
                            OR
                            Tracking.ChangedTo IN ('Cancelled by ILL Staff', 'Request Finished')
                        )
join_tables:
  - INNER JOIN Tracking ON Tracking.TransactionNumber = Transactions.TransactionNumber AND Transactions.ProcessType IN ('DocDel', 'Doc Del')
group_by_columns:
  - "Tracking.TransactionNumber"
  - "Transactions.RequestType"
  - "Tracking.ChangedTo"
export_file_name:      "doc_del.csv"
export_filter_date_sql: "Tracking.DateTime > ?"
export_filter_date_range_sql: "Tracking.DateTime > ? AND Tracking.DateTime < ?"

# Target Config
target_adapter:        csv
target_model:          "Illiad::DocDel"
truncate_before_load:  "yes"
legacy_filter_date_field: "transaction_date"
