load_sequence:         12
target_adapter:        'native_sql'
target_model:          "Illiad::LendingTracking"
truncate_before_load:  "yes"
sqls:
  - |
                        INSERT INTO illiad_lending_trackings (
                                  institution_id,
                                  transaction_number,
                                  request_type,
                                  arrival_date,
                                  completion_date,
                                  completion_status,
                                  created_at,
                                  updated_at
                        )
                        SELECT    %{institution_id},
                                  L1.transaction_number,
                                  L1.request_type,
                                  L1.transaction_date,
                                  L2.transaction_date,
                                  L3.status,
                                  NOW(),
                                  NOW()
                        FROM  (
                          SELECT
                            institution_id,
                            transaction_number,
                            MIN(transaction_date) AS transaction_date,
                            request_type
                          FROM illiad_lendings
                          WHERE institution_id = %{institution_id}
                            AND status IN (
                              'Awaiting Lending Request Processing',
                              'Awaiting Local Request Processing',
                              'Imported from OCLC',
                              'Imported from DOCLINE'
                            )
                          GROUP BY institution_id, transaction_number, request_type
                        ) L1
                        LEFT JOIN (
                          SELECT
                            institution_id,
                            transaction_number,
                            MIN(transaction_date) AS transaction_date
                          FROM illiad_lendings
                          WHERE institution_id = %{institution_id}
                            AND status IN (
                              'Request Conditionalized',
                              'Item Shipped',
                              'Request Finished'
                            )
                            GROUP BY institution_id, transaction_number
                          ) L2
                        ON L1.institution_id = L2.institution_id
                          AND L1.transaction_number = L2.transaction_number
                        LEFT JOIN illiad_lendings L3
                        ON L1.institution_id = L3.institution_id
                          AND L1.transaction_number = L3.transaction_number
                          AND L2.transaction_date = L3.transaction_date
                          AND L3.status IN (
                            'Request Conditionalized',
                            'Item Shipped',
                            'Request Finished'
                          )
                        WHERE L1.institution_id = %{institution_id};

  - |
                        UPDATE illiad_lending_trackings LT
                        SET completion_date = L.transaction_date,
                            completion_status = L.status
                        FROM illiad_lendings L
                        WHERE status = 'Cancelled by ILL Staff'
                          AND L.transaction_number = LT.transaction_number
                          AND L.institution_id = LT.institution_id
                          AND L.institution_id = %{institution_id}
                          AND LT.completion_status <> L.status;

  - |
                        VACUUM ANALYZE illiad_lending_trackings;
