load_sequence:         12
target_adapter:        'native_sql'
target_model:          "Illiad::LendingTracking"
truncate_before_load:  "yes"
sqls:
  - |
                        INSERT INTO illiad_lending_trackings (
                                  institution_id,
                                  transaction_number,
                                  request_type,
                                  arrival_date,
                                  created_at,
                                  updated_at
                        )
                        SELECT    %{institution_id},
                                  transaction_number,
                                  request_type,
                                  MIN(transaction_date),
                                  NOW(),
                                  NOW()
                        FROM  illiad_lendings
                        WHERE institution_id = %{institution_id}
                          AND status IN (
                            'Awaiting Lending Request Processing',
                            'Awaiting Local Request Processing',
                            'Imported from OCLC',
                            'Imported from DOCLINE'
                          )
                        GROUP BY transaction_number, request_type;

  - |
                        UPDATE illiad_lending_trackings LT
                        SET completion_date = L.transaction_date,
                            completion_status = L.status
                        FROM illiad_lendings L
                        WHERE status = 'Cancelled by ILL Staff'
                          AND L.transaction_number = LT.transaction_number
                          AND L.institution_id = LT.institution_id
                          AND L.institution_id = %{institution_id};

  - |
                        UPDATE illiad_lending_trackings LT
                        SET completion_date = L.transaction_date,
                            completion_status = L.status
                        FROM illiad_lendings L
                        INNER JOIN (
                          SELECT
                            transaction_number,
                            institution_id,
                            MIN(transaction_date) AS transaction_date
                          FROM illiad_lendings
                          WHERE institution_id = %{institution_id}
                            AND status IN (
                              'Request Conditionalized',
                              'Item Shipped',
                              'Request Finished'
                            )
                          GROUP BY transaction_number, institution_id
                        ) L2
                        ON L.transaction_number = L2.transaction_number
                          AND L.transaction_date = L2.transaction_date
                          AND L.institution_id = L2.institution_id
                        WHERE L.transaction_number = LT.transaction_number
                          AND L.institution_id = LT.institution_id
                          AND L.institution_id = %{institution_id}
                          AND LT.completion_date IS NULL;
