load_sequence:         13
target_adapter:        'native_sql'
target_model:          "Illiad::DocDelTracking"
truncate_before_load:  "yes"
sqls:
  - |
                        INSERT INTO illiad_doc_del_trackings (
                                  institution_id,
                                  transaction_number,
                                  request_type,
                                  arrival_date,
                                  created_at,
                                  updated_at
                        )
                        SELECT    %{institution_id},
                                  transaction_number,
                                  request_type,
                                  MIN(transaction_date),
                                  NOW(),
                                  NOW()
                        FROM  illiad_doc_dels
                        WHERE institution_id = %{institution_id}
                          AND status IN (
                            'Submitted by Customer',
                            'Request Added Through Client',
                            'Request Added through Web Platform'
                          )
                        GROUP BY transaction_number, request_type;

  - |
                        UPDATE illiad_doc_del_trackings DT
                        SET completion_date = D.transaction_date,
                            completion_status = D.status
                        FROM illiad_doc_dels D
                        WHERE status = 'Cancelled by ILL Staff'
                          AND D.transaction_number = DT.transaction_number
                          AND D.institution_id = DT.institution_id
                          AND D.institution_id = %{institution_id};

  - |
                        UPDATE illiad_doc_del_trackings DT
                        SET completion_date = D.transaction_date,
                            completion_status = D.status
                        FROM illiad_doc_dels D
                        INNER JOIN (
                          SELECT
                            transaction_number,
                            institution_id,
                            MIN(transaction_date) AS transaction_date
                          FROM illiad_doc_dels
                          WHERE institution_id = %{institution_id}
                            AND status IN (
                              'Item Found',
                              'Delivered to Web',
                              'Request Conditionalized',
                              'Request Finished'
                            )
                          GROUP BY transaction_number, institution_id
                        ) D2
                        ON D.transaction_number = D2.transaction_number
                          AND D.transaction_date = D2.transaction_date
                          AND D.institution_id = D2.institution_id
                        WHERE D.transaction_number = DT.transaction_number
                          AND D.institution_id = DT.institution_id
                          AND D.institution_id = %{institution_id}
                          AND DT.completion_date IS NULL;
