load_sequence:         15
target_adapter:        'native_sql'
target_model:          "Illiad::LendingTracking"
purge_legacy_data_before_load:  "no"
sql: |
                        UPDATE illiad_lending_trackings
                        SET turnaround = DATE_PART('day', completion_date - arrival_date)
                        WHERE institution_id = %{institution_id}
                        ;
